### ISSUE TITLE
Possible algo

### ISSUE THREAD

**Issue by YannisDC** [frankbryce/assembly-theory#1]
Have a look at [my repo](https://github.com/YannisDC/PathwayAssembly) in case you’re stuck. Would love to see some more code for PA. Excited to ser yours.

**Comment by frankbryce** [comment]
Hi there, thanks for the kick in the butt! I'd attempted and indeed got stuck one night over a month ago. I took a stab at a data model first in a change today. I think this is a better model than strings, because it could work for any object, such as a molecule.

I am intending for the Path object to be immutable once created, though I don't have this restricted yet in the API. Just got something working to have you see my thinking here. Happy to collaborate on implementations in several languages. I think if we come up with a reasonably fast algorithm it could be useful to many people. Keep in mind this is NP complete, so "fast" will be quite relative.

**Comment by frankbryce** [comment]
I actually had a brain wave after making this data structure (and discovered some small bugs since my last post) but it appears that a basic algorithm for an arbitrarily nested assembly can work now. I implemented a string assembler, but so long as the object you want to assemble implements an "in" operator in python, then this should also work. It's not fast, but for now I'll close this.

Thanks again for the ping!

**Comment by frankbryce** [comment]
Feel free to reopen and continue discussion.
